name: Validation

on:
  push:
    branches: [ "main", "develop"]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  validate_homeworks:
    name: Validate all homeworks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check flake8
        run: flake8 .

      - name: Check pylint
        if: ${{ always() }}
        run: pylint ./*/*.py

      - name: Check tests with unittest 01
        if: ${{ always() }}
        run: cd 01 && python3 -m unittest *.py
        
      - name: Check tests with unittest 02
        if: ${{ always() }}
        run: cd 02 && python3 -m unittest *.py
        
      - name: Run tests with coverage
        run: |
          coverage run -m unittest
  
      - name: Generate coverage report
        run: |
          coverage report
