name: Validation

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  validate_homeworks:
    name: Validate all homeworks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check flake8
        run: flake8 .

      - name: Check pylint
        if: ${{ always() }}
        run: pylint ./*/*.py

      - name: Run tests with unittest
        if: ${{ always() }}
        run: |
          for dir in 01 02; do
            (cd $dir && python3 -m unittest *.py)
          done

      - name: Run tests with coverage
        run: |
          for dir in 01 02; do
            (cd $dir && coverage run -m unittest)
          done

      - name: Generate coverage report
        run: coverage report -m 01/*.py 02/*.py
